config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :property_types
  resources :orders
  get 'admin' => 'admin#index', as: 'admin'

  get 'choice_property_type' => 'orders#choice_property_type', as: 'choice_property_type'
  get 'about_property' => 'orders#about_property', as: 'about_property'
  get 'exterior' => 'orders#exterior', as: 'exterior'
  get 'still_photo' => 'orders#still_photo', as: 'still_photo'
  get 'floor_plan' => 'orders#floor_plan', as: 'floor_plan'
  get 'custome_domain' => 'orders#custome_domain', as: 'custome_domain'
  get 'review' => 'orders#review', as: 'review'
  root 'orders#choice_property_type'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :property_type
  belongs_to :photo
  validates :property_type_id, :photo_id, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :orders
  validates :title, presence: true
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  has_many :orders
  validates :title, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order

  def choice_property_type
    @property_types = PropertyType.all
    @property_type_id = (@order.property_type == nil) ? 1 : @order.property_type.id

    respond_to do |format|
      format.html
      format.js
    end
  end

  def about_property
    if params[:id]
      @order.property_type_id = params[:id]
      @order.save
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def exterior
    respond_to do |format|
      format.html
      format.js
    end
  end

  def still_photo
    @photos = Photo.all
    @photo_id = (@order.photo == nil) ? 1 : @order.photo.id
    if params[:id]
      @order.exterior_tour = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def floor_plan
    @photo_id = (@order.photo == nil) ? 1 : @order.photo.id
    if params[:id]
      @order.photo_id = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def custome_domain
    if params[:id]
      @order.floor_plan = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def review
    if params[:id]
      @order.custome_domain = params[:id]
      @order.save
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @orders = Order.page(params[:page]).per(10)
    
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @property_types = PropertyType.all
    @photos = Photo.all
  end

  def edit
    @order = Order.find(params[:id])
    @property_types = PropertyType.all
    @photos = Photo.all
  end

  def create
    @order = Order.new(order_params)
   
    if @order.save
      redirect_to orders_path
    else
      @property_types = PropertyType.all
      @photos = Photo.all
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])
    if params[:redirect_to_orders]
      if @order.update(order_params)
        redirect_to orders_path
      else
        @property_types = PropertyType.all
        @photos = Photo.all
        render 'edit'
      end
    else
      @order.update(order_params)
      redirect_to exterior_path
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
 
    redirect_to orders_path
  end

  private

    def set_order
      @order = Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
      @order = Order.create(property_type_id: 1, photo_id: 1)
      session[:order_id] = @order.id
    end

    def order_params
      params.require(:order).permit(:property_type_id, :property_address, :sqft,
                                    :number_of_units, :exterior_tour,
                                    :floor_plan, :photo_id, :custome_domain,
                                    :detach_space)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.page(params[:page]).per(10)
    
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(photo_params)
   
    if @photo.save
      redirect_to photos_path
    else
      render 'new'
    end
  end

  def update
    @photo = Photo.find(params[:id])
   
    if @photo.update(photo_params)
      redirect_to photos_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
 
    redirect_to photos_path
  end

  private
    def photo_params
      params.require(:photo).permit(:title)
    end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController

  def index
    @property_types = PropertyType.page(params[:page]).per(10)
    
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def show
    @property_type = PropertyType.find(params[:id])
  end

  def new
    @property_type = PropertyType.new
  end

  def edit
    @property_type = PropertyType.find(params[:id])
  end

  def create
    @property_type = PropertyType.new(property_type_params)
   
    if @property_type.save
      redirect_to property_types_path
    else
      render 'new'
    end
  end

  def update
    @property_type = PropertyType.find(params[:id])
   
    if @property_type.update(property_type_params)
      redirect_to property_types_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @property_type = PropertyType.find(params[:id])
    @property_type.destroy
 
    redirect_to property_types_path
  end

  private
    def property_type_params
      params.require(:property_type).permit(:title)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def active_property_type property_type_id
    return 'active' if @order.property_type == nil && property_type_id == 1
    (@order.property_type == nil || @order.property_type.id != property_type_id) ? '' : 'active'
  end

  def active_still_photo photo_id
    return 'active' if @order.photo == nil && photo_id == 1
    (@order.photo == nil || @order.photo.id != photo_id) ? '' : 'active'
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/property_types_helper.rb
module PropertyTypesHelper
end

app/views/admin/index.html.erb
<% provide(:admin, 'active') %>
<div class="admin-panel">
  <h1>Admin panel</h1>
  <div>
    <%= link_to 'Orders', orders_path, class: "btn btn-info" %>
    <%= link_to 'Property types', property_types_path, class: "btn btn-info" %>
    <%= link_to 'Photo types', photos_path, class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walkintour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <div id="content">
      <%= render 'shared/header' %>

      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </div>

</body>
</html>

app/views/orders/_about_property_remote.html.erb
<div id="walkintour">
  <%= image_tag 'walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag '3d-image.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Tell us more about Your Property
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<%= form_for @order, remote: true do |f| %>

  <div id="tab-types">
    <div class="control-label">
      <%= f.label :property_address %>
    </div>
    <div>
      <%= f.text_area :property_address, autofocus: true,
                       placeholder: 'Property Address, City, State, Zip Code' %>
    </div>

    <div class="control-label padding-top-label">
      <%= f.label :sqft %>
    </div>
    <div class="form-control">
      <%= f.text_field :sqft, size: 22, placeholder: 'Property Sqft' %>
    </div>

    <div class="control-label padding-top-label">
      Access
    </div>
    <div class="pick-appointment">
      <%= link_to 'Click to Pick Appointment Preferences', '#' %>
    </div>

    <div class="control-label padding-top-label">
      Number of Units
    </div>
    <div class="numbers">
      <div class="minus" id="number-of-units-minus">-</div>
      <div><%= f.text_field :number_of_units, readonly: true, id: "number" %></div>
      <div class="plus" id="number-of-units-plus">+</div>
    </div>

    <div class="control-label padding-top-label clear-left">
      Additional Detach Space <span>like Attic/Basement&amp;Buildings</span>
    </div>

    <div class="numbers">
      <div class="minus" id="detach-space-minus">-</div>
      <div><%= f.text_field :detach_space, readonly: true, id: "detach-space" %></div>
      <div class="plus" id="detach-space-plus">+</div>
    </div>

  </div>

  <div id="bellow-options">

    <div id="bellow-previous">
      <%= link_to choice_property_type_path, remote: true do %>
        <span id="previous">&lt;</span>
        PREVIOUS
      <% end %>
    </div>

    <div id="bellow-slider">
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
    </div>

    <div id="bellow-next">
      <%= f.submit "NEXT >", class: 'submit-next', remote: true %>
    </div>

  </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $(".minus").click(function() {
      if($(this).attr("id") == "number-of-units-minus") {
        var i = parseInt($("#number").val());
        i = (--i < 0)? 0 : i;
        $("#number").val(i);
      }
      else {
        var i = parseInt($("#detach-space").val());
        i = (--i < 0)? 0 : i;
        $("#detach-space").val(i);
      }
    });

    $(".plus").click(function() {
      if($(this).attr("id") == "number-of-units-plus") {
        var i = parseInt($("#number").val());
        i = (++i < 0)? 0 : i;
        $("#number").val(i);
      }
      else {
        var i = parseInt($("#detach-space").val());
        i = (++i < 0)? 0 : i;
        $("#detach-space").val(i);
      }
    });
  });
</script>

app/views/orders/_choice_property_type_remote.html.erb
<div id="walkintour">
  <%= image_tag 'walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag '3d-image.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Tell us more about Your Property Type
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">

  <% @property_types.each do |property_type| %>
    <div class="tab-type <%= active_property_type property_type.id %>" id="<%= property_type.id %>">
      <div class="type">
        <%= property_type.title %>
      </div> 
      <div class="type-image"><%= image_tag 'type-image.png' %></div>
    </div>
  <% end %>

</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to '#' do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-green.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to about_property_path(id: @property_type_id), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>

</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/about_property?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_custome_domain_remote.html.erb
<div id="walkintour">
  <%= image_tag 'custome-domain-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'custome-domain.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Custome Domain to Your Website
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">
  <div class="tab-type <%= @order.custome_domain ? '' : 'active' %>" id="false">
    <div class="type">
      No Custome Domain
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>

  <div class="tab-type <%= @order.custome_domain ? 'active' : '' %>" id="true">
    <div class="type">
      Add Custome Domain (+19.99)
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to floor_plan_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
       <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to review_path(id: @order.custome_domain), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'custome-domain-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- Included with every order, our attractive website templatetakes only minutes to modify
</div>
<div class="paragraph">- Add a custom domain to make your single property  websiteeas to remember
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/review?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_exterior_remote.html.erb
<div id="walkintour">
  <%= image_tag 'exterior-tour-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'exterior-tour.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Exterior WALKINTOUR
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">
  <div class="tab-type <%= @order.exterior_tour ? '' : 'active' %>" id="false">
    <div class="type">
      No Exterior WALKINTOUR
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>

  <div class="tab-type <%= @order.exterior_tour ? 'active' : '' %>" id="true">
    <div class="type">
      Add Exterior WALKINTOUR (+100)
    </div> 
    <div class="type-image"><%= image_tag 'type-image.png' %></div>
  </div>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to about_property_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-green.png' %> <%= image_tag 'sl-gray.png' %>
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to still_photo_path(id: @order.exterior_tour), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'exterior-tour-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- We have revolutionaized the visualization of outdoor space so that you acn feature the exterior selling points of your 3D WALKINTOUR. Give your buyers the freedom to explore the entirety of the property, experienceing the home inside and out.
</div>
<div class="paragraph">- Further distinguish our marketing strategy by adding an Exterioir WALKINTOUR to your order
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/still_photo?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_property_type_remote.html.erb
<div id="walkintour">
  <%= image_tag 'walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag '3d-image.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Tell us more about Your Property Type
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">

  <% @property_types.each do |property_type| %>
    <div class="tab-type <%= active_property_type property_type.id %>" id="<%= property_type.id %>">
      <div class="type">
        <%= property_type.title %>
      </div> 
      <div class="type-image"><%= image_tag 'type-image.png' %></div>
    </div>
  <% end %>

</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to '#' do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-green.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to about_property_path(id: @property_type_id), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>

</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/about_property?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/_still_photo_remote.html.erb
<div id="walkintour">
  <%= image_tag 'exterior-tour-walkintour.png' %>
</div>
<div id="image-3d">
  <%= image_tag 'still-photo.png' %>
</div>

<%= render 'shared/configuration_header' %>

<div id="configuration-types">
  <div id="configuration-type">
    Add Still Photo
  </div>
  <div id="types-que">
    <%= image_tag 'types_que.png' %>
  </div>
</div>

<div id="tab-types">

  <% @photos.each do |photo| %>
    <div class="tab-type <%= active_still_photo photo.id %>" id="<%= photo.id %>">
      <div class="type<%= photo.id != 1 ? '-rows' : '' %>">
        <%= photo.title %>
      </div> 
      <div class="type-image"><%= image_tag 'type-image.png' %></div>
    </div>
  <% end %>
</div>

<div id="bellow-options">

  <div id="bellow-previous">
    <%= link_to exterior_path, remote: true do %>
      <span id="previous">&lt;</span>
      PREVIOUS
    <% end %>
  </div>

  <div id="bellow-slider">
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-green.png' %>
      <%= image_tag 'sl-gray.png' %> <%= image_tag 'sl-gray.png' %>
  </div>

  <div id="bellow-next">
    <%= link_to floor_plan_path(id: @photo_id), remote: true, class: 'active', id: 'next' do %>
      NEXT
      <span>&gt;</span>
    <% end %>
  </div>
</div>

<div class="clear"></div>
<div class="exterior-tour-plus">
  <%= image_tag 'still-photo-plus.png' %>
</div>
<div class="exterior-tour-plus-fon"></div>
<div class="paragraph">- we can create traditional home layouts more quickly and affordably than ever before.
</div>
<div class="paragraph">- Hand out our new-construction style flor plan featuring your branding to make a lasting impressing on your buyers and sellers (required 2-3 business days to create)
</div>

<script type="text/javascript">
  $(document).ready(function() {

    $(".tab-type").click(function() {
      if (!$(this).hasClass("active")) {
        $(".tab-type").removeClass("active");
        $(this).addClass("active");

        $("#next").attr("href", "/floor_plan?id=" + $(this).attr("id"));
      }
    });

  });
</script>

app/views/orders/about_property.html.erb
<% provide(:orders, 'active') %>
<div id="main-fon">
  <div id="main">
    <%= render 'about_property_remote' %>
  </div>
  <%= render 'shared/content_bottom' %>
</div>

app/views/orders/about_property.js.erb
$('#main').html('<%= escape_javascript render(partial: "about_property_remote") %>');

app/views/orders/custome_domain.js.erb
$('#main').html('<%= escape_javascript render(partial: "custome_domain_remote") %>');

app/views/orders/edit.html.erb
<div class="admin-panel">
  <h1>Edit order</h1>

  <%= render partial: 'form', locals: { title_sumbit: 'Save order' } %>
</div>

app/views/orders/new.html.erb
<div class="admin-panel">
  <h1>Create new order</h1>

  <%= render partial: 'form', locals: { title_sumbit: 'Create order' } %>
</div>

app/views/orders/review.js.erb
$('#main').html('<%= escape_javascript render(partial: "review_remote") %>');

app/views/orders/show.html.erb
<div class="admin-panel">
  <h1>Order: <%= @order.id %></h1>
  <ul>
    <li>Id: <%= @order.id %></li>
    <li>Property type: <%= @order.property_type.title %></li>
    <li>Property address: <%= @order.property_address %></li>
    <li>Sqft: <%= @order.sqft %></li>
    <li>Number of units: <%= @order.number_of_units %></li>
    <li>Exterior tour: <%= @order.exterior_tour ? 'Yes' : 'No' %></li>
    <li>Floor plan: <%= @order.floor_plan ? 'Yes' : 'No' %></li>
    <li>Photo type: <%= @order.photo.title %></li>
    <li>Custome domain: <%= @order.custome_domain ? 'Yes' : 'No' %></li>
    <li>Detach space: <%= @order.detach_space %></li>
  </ul>
  <div><%= button_to 'Back', orders_path, method: :get, class: "btn btn-default" %></div>
</div>

app/views/orders/still_photo.js.erb
$('#main').html('<%= escape_javascript render(partial: "still_photo_remote") %>');

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :title %>
  </div>

  <div>
    <%= f.text_field :title, size: 45 %>
  </div>

  <div class="group-submit">
    <%= f.submit title_sumbit, class: "btn btn-primary" %>
    <%= link_to 'Сancel', :back, class: "btn btn-default" %>
  </div>

<% end %>

app/views/photos/_photo.html.erb
<tr>
  <td class="right"><%= photo.id %></td>
  <td><%= link_to photo.title, photo_path(photo) %></td>
  <td><%= button_to 'Edit', edit_photo_path(photo),
                     method: :get, class: "btn btn-success btn-xs" %></td>
  <td><%= button_to 'Delete', photo_path(photo),
                     method: :delete,
                     data: { confirm: 'Are you sure?' },
                     class: "btn btn-danger btn-xs" %></td>
</tr>

app/views/photos/edit.html.erb
<div class="admin-panel">
  <h1>Edit photo type</h1>

  <%= render partial: 'form', locals: { title_sumbit: 'Save photo type' } %>
</div>

app/views/photos/index.html.erb
<div class="admin-panel">
  <h1>Photo types</h1>
  <p>
    <%= button_to new_photo_path, method: :get, class: 'btn btn-primary' do %>
      <span class="glyphicon"></span>
      Add photo type
    <% end %>
  </p>

  <% if @photos.empty? %>
    <b>No photo types</b>
  <% else %>

  <div class="table-index">
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Title</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody id="photos">
        <%= render partial: "photo", :collection => @photos, as: :photo %>
      </tbody>
    </table>
  </div>
  <div id="paginator", class="paginate-centre">
    <%= paginate @photos, remote: true %>
  </div>
  <% end %>

  <p>
    <%= button_to 'Back', admin_path, method: :get, class: "btn btn-default" %>
  </p>
</div>

app/views/photos/index.js.erb
$('tbody#photos').html('<%= escape_javascript render(partial: "photo", :collection => @photos, :as => :photo) %>');

$('#paginator').html('<%= escape_javascript(paginate(@photos, :remote => true).to_s) %>');

app/views/photos/new.html.erb
<div class="admin-panel">
  <h1>Create new photo type</h1>

  <%= render partial: 'form', locals: { title_sumbit: 'Create photo type' } %>
</div>

app/views/photos/show.html.erb
<div class="admin-panel">
  <h1><%= @photo.title %></h1>
  <ul>
    <li>Id: <%= @photo.id %></li>
  </ul>
  <div><%= button_to 'Back', photos_path, method: :get, class: "btn btn-default" %></div>
</div>

app/views/property_types/_form.html.erb
<%= form_for @property_type do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div>
    <%= f.label :title %>
  </div>

  <div>
    <%= f.text_field :title, size: 22 %>
  </div>

  <div class="group-submit">
    <%= f.submit title_sumbit, class: "btn btn-primary" %>
    <%= link_to 'Сancel', :back, class: "btn btn-default" %>
  </div>

<% end %>

app/views/property_types/_property_type.html.erb
<tr>
  <td class="right"><%= property_type.id %></td>
  <td><%= link_to property_type.title, property_type_path(property_type) %></td>
  <td><%= button_to 'Edit', edit_property_type_path(property_type),
                     method: :get, class: "btn btn-success btn-xs" %></td>
  <td><%= button_to 'Delete', property_type_path(property_type),
                     method: :delete,
                     data: { confirm: 'Are you sure?' },
                     class: "btn btn-danger btn-xs" %></td>
</tr>

app/views/property_types/edit.html.erb
<div class="admin-panel">
  <h1>Edit property type</h1>

  <%= render partial: 'form', locals: { title_sumbit: 'Save property type' } %>
</div>

app/views/property_types/index.html.erb
<div class="admin-panel">
  <h1>Property types</h1>
  <p>
    <%= button_to new_property_type_path, method: :get, class: 'btn btn-primary' do %>
      <span class="glyphicon"></span>
      Add property type
    <% end %>
  </p>

  <% if @property_types.empty? %>
    <b>No property types</b>
  <% else %>

  <div class="table-index">
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Title</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody id="property_types">
        <%= render partial: "property_type", :collection => @property_types, as: :property_type %>
      </tbody>
    </table>
  </div>
  <div id="paginator", class="paginate-centre">
    <%= paginate @property_types, :remote => true %>
  </div>
  <% end %>

  <p>
    <%= button_to 'Back', admin_path, method: :get, class: "btn btn-default" %>
  </p>
</div>

app/views/property_types/index.js.erb
$('tbody#property_types').html('<%= escape_javascript render(partial: "property_type", :collection => @property_types, :as => :property_type) %>');

$('#paginator').html('<%= escape_javascript(paginate(@property_types, :remote => true).to_s) %>');